language: python
cache: pip
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
script:
  - py.test --cov=kotor
  - bash <(curl -s https://codecov.io/bash)